README.md

fix(doc): updated documentation for running project on windows

---

README.md

Hi everyone 😃,
I followed these steps and I got a token at the end. When I ran the local start script I got `Ready LOCAL!`, which means it worked.
@eddiejaoude if you got the token another way (maybe a simpler way), I'd be happy to change the README with a list of steps, or another documentation link. I didn't add a list of steps on the README since the link seems to explain it thoroughly.
Closes: #28

Update README with link to help getting a discord token

---

README.md
src/index.ts
src/notifyGeneralChannel.ts

Feature 31 notify general when a new channel is created

---

src/index.ts

Here is an example of what the bot would look like:

feat(bot): add a presence to the bot

---

src/commandHandlers/codeOfConduct.ts
src/commandHandlers/fallback.ts
src/commandHandlers/help.ts
src/commandHandlers/index.ts
src/commandHandlers/standup.ts
src/commandHandlers/stats.ts
src/commands.ts

To be reviewed after PR #48 as this contains those changes as well, once #48 is merged this PR will be much clearer

feat(command): standup command #50

---

README.md

fix(docs): add a line between "Appearance" and screenshots

---

src/commandHandlers/codeOfConduct.ts
src/commandHandlers/help.ts
src/commandHandlers/standup.ts
src/commandHandlers/stats.ts

Add in a usage parameter to commands.
Add in the usage message onto the help command.
Example:
Adds #59

feature(usage): Add in a usage parameter to commands

---

README.md

@garretcharp let me know if there is something I got wrong about the command handlers separation you made, or if there is something we should add 👍
Closes: #18

docs(commands): add section about creating a new command

---

.github/workflows/master.yaml
README.md
package-lock.json
package.json
src/commandHandlers/stats.service.ts
src/config.ts
src/guildMemberAdd.ts
src/index.ts
src/logger.ts
src/notifyGeneralChannel.ts
tslint.json

feat(logger): log to console and discord bot channel #42

---

.github/workflows/master.yaml
.gitignore
README.md
package-lock.json
package.json
src/commandHandlers/bio.ts
src/commandHandlers/index.ts
src/config.ts
src/firebase.ts

Setting my bio data:
Reading my bio data:
Reading someone else's bio:

feat(bio): save/read user bio + socials #60

---

package-lock.json
package.json
src/config.ts
src/index.ts
src/timezone.ts

Closes #80 
Can write any message in the chat with 
- `1pm UTC`
- `1:30pm UTC`

feat(timezone): listen for timezone and give alternatives #80

---

src/config.ts

Fixes #89 
Added IST abbrevation in TIMEZONES

Added IST in TIMEZONES

---

src/commandHandlers/bio.ts
src/commandHandlers/iam.ts
src/commandHandlers/index.ts
src/commandHandlers/roles.ts
src/config.ts
src/messageReactionAdd.ts

_Note_: This command needs the permission "Managed Roles" in order to work:
closes #74

feat(roles): add `iam` role assignment command and role descriptions

---

package-lock.json
package.json
src/commandHandlers/index.ts
src/commandHandlers/reminder.ts
src/notifyGeneralChannel.ts
src/scheduler.service.ts

closes: #81 
Screenshot with the received DM:
_Note_: It says the message was received at 22:48 (aka 10:48), but it was indeed received at 22:49 since the 48th minute was when I sent the reminder command.

feat(scheduler): Add Reminder command

---

src/commandHandlers/bio.ts
src/commandHandlers/guild.service.ts

Using the `bio` command like before, but the user's **roles** are appended to the end...

feat(bio): users roles appended to bio #96

---

src/commandHandlers/iam.ts
src/config.ts

feat(roles): save users roles in the db

---

src/commandHandlers/iam.ts

fix(iam): self assign roles promise error

---

src/index.ts
src/messageReactionAdd.ts

feat(reactions): author can not get points for their own reactions

---

src/config.ts

feat(roles): more self assign roles #130

---

src/commandHandlers/codeOfConduct.ts
src/config.ts

fix: updated project url in config & codeOfConduct(#82)

---

package-lock.json
package.json
src/commandHandlers/bio.ts
src/config.ts
src/eventStream.ts
src/index.ts

feat(events): save event stream to db

---

src/commandHandlers/bio.ts

feat(bio): added example when no user is found #144

---

src/commandHandlers/bio.ts

fix(bio): roles only show if user has a role #149

---

package.json

fix: update repository urls in package.json

---

src/timezone.ts

fix(timezone): added lowercase timezone support #148

---

src/commandHandlers/bio.ts

feat(bio): Twitter handle converted into link

---

src/commandHandlers/bio.ts
src/timezone.ts

closes #145
closes #96
I updated the bio command to have timezone as one of the keys

Updated config.ts bio command

---

src/commandHandlers/bio.ts

fix(bio): fixed error in get information logic #167

---

.all-contributorsrc
README.md

I have resolved the conflicts in this branch.

Resolved conflicts

---

nodemon.json
package-lock.json
package.json

feat: command to watch and compile on save #143

---

src/commandHandlers/support.ts
src/messageReactionAdd.ts

Users gets `high value` role more than once

---

src/commandHandlers/bio.ts

fix(bio): get location string #133

---

src/logger.ts

fix(logger): Updated MessageLogic #202

---

src/commandHandlers/bio.ts

fix(bio): Mentioned Users show roles #147

---

src/commandHandlers/bio.ts

fix(bio): allow pipe characters in description #131

---

src/commandHandlers/bio.ts
src/config.ts

feat(bio): delete bio #208

---

src/commandHandlers/iam.ts

closes #120 
Allows user to assign more than one role.

feat(iam): allow more than one role to be assigned #120

---

src/commandHandlers/iam.ts

fix(iam): trim whitespace from arguments #216

---

.github/workflows/community.yml

feat(actions): community GitHub Action

---

src/commandHandlers/iam.ts
src/commandHandlers/tips/opensource.service.ts
src/config.ts
tips/openSourceResources.md
tips/openSourceTips.md

feat(tips): move tips into markdown files #94

---

.github/workflows/stale.yaml

- Added Stale action from support repo

Added stale action

---

README.md

Changed some text in README.md. It's still not 100% clear to me, but it's a start.

Mikeychanges

---

src/commandHandlers/bio.ts

closes #211 & closes #237 & closes #234

fix(bio): check for valid bio #211

---

src/config.ts
src/index.ts
src/words.ts

feat(suggestions): words show with alternatives

---

src/config.ts
src/words.ts

fix(words): prepend words to reduce noise #248

---

src/commandHandlers/roles.ts

closes #260 
Updated the choice of words and added example under the rolesList.

Improved the self assign roles command docs

---

src/commandHandlers/support.ts

closes #230
I decided to make it more generic.

feat(support): send user to select category for new discussion #230

---

CONTRIBUTING.md

docs(contributing): fix link to code of conduct

---

src/config.ts
src/words.ts

fix(words): checking for space and period after word #268

---

README.md

docs: instructions for running locally (#272)

---

src/index.ts

fix: schedules reminder after bot is ready

---

src/commandHandlers/iam.ts

closes #240 
I have fixed an inconsistent occurrence of the term `updateAt` and `updatedAt` according to issue #240

fixed inconsistency in database writes

---

.github/workflows/stale.yaml

Updated the stale action close later
Closes #281

feat: Updated days before close on stale action

---

src/config.ts

Added timezones for
- Stockholm, Sweden
- Helsinki, Finland (winter time)
- Helsinki, Finland (summer time)

Timezone values added

---

README.md

docs(features): add description to server status

---

README.md
package-lock.json
package.json

closes #278 
This tool can help others with making commit messages with conventional change log

Feat/commitizen #278

---

src/commandHandlers/help.ts

closes https://github.com/EddieJaoudeCommunity/EddieBot/issues/292
:upside_down_face:

feat: added optional arguments to the help command

---

src/words.ts

This PR slightly modifies the verbiage of the "inclusive word choices" embed, to make the connotation more gentle.

Change wording

---

src/config.ts
src/timezone.ts

This resolves issue #232
There was another PR made for the same #305 
This new PR was made as the other branch will be used later for dependencies-fix(It is broken as of now).
The fixes included in this pr are:
1- most major timezones have been added
2- embeds of the timezone command fixed to prevent text-walling the chat.
BEFORE:
AFTER:
closes #232

fix(issue-232): Added popular Timezones + embed fix

---

src/config.ts

fix: added 'moaning' to Alexjs config

---

src/config.ts

deals with the CI failure on `lint` test in issue- #303  ( PR- #307 ) branch after recent commits ( from #307 and #333 )

fix: linted code in issue-303 branch

---

src/config.ts
src/timezone.ts

This fixes the timezone command being a wallblock
Resolves #315

Issue315 timezones(brief)

---

src/commandHandlers/help.ts

fix: made help command concise

---

src/commandHandlers/help.ts

fix(bot) : Fixed 'or' issue in help embed for standup

---

src/config.ts

Closes#318 
PR for this [issue](https://github.com/EddieJaoudeCommunity/EddieBot/issues/318).

Added "special" to ignore list

---

.github/ISSUE_TEMPLATE/bug.md

Added an issue template for the contributors to raise issues more effectively.

Created an issue template

---

src/config.ts

Changed allowed words and added examples for the problem

fix: improved config.ts

---

README.md

Added a small paragraph to describe how to add to the list of allowed words.
This is in response to Issues #354 and #320

Added documentation for allowed words

---

README.md

closes #358 
Removed Production badge as per issue.

docs: update badges #358

---

src/config.ts

Changed the `defaultEmbed()` function so as to have a parameter for **color** that is defaulted to this color `#0099ff` (blue).
This change is in response to Issue #372.

added parameter `color`

---

README.md

created a documentation section and added the discord.js link under resources

add-discordjs-link-readme #380

---

src/commandHandlers/bio.ts

This is following the discussion on #378

added codeblocks for bio command #378

---

README.md
docs/addcommand.md
docs/allowedwords.md
docs/banexample.md
docs/database.md
docs/gatewayintents.md

partially completes issue #387

docs: move examples

---

README.md

Updated features list with Alex Feature closes #388

docs: Updated Features

---

src/commandHandlers/roles.ts

Fixed the 'example of usage' message in roles.ts

---

docs/allowedwords.md

Fixed the broken link in allowedwords.md

---

src/config.ts

added a few more language roles such as nim, go e.t.c

Added Language Roles

---

src/config.ts

added 'moan' to ignore list

---

package-lock.json
src/commandHandlers/roles.ts

The `roles` command covered up a lot of screen estate.
This PR introduces the following to the command: argument parsing, concise embed
Are there better ways of doing this? Could the code be made more efficient and concise?
Also, should some of the redundant code be removed using helper functions?
| Changes 
| :-:
| - Embed data is arranged more cleanly. The roles are comma-separated paragraph at the top and the ones with extra description are added at the bottom in this format: `role-name - description` ![Screenshot 2021-01-28 at 4 54 55 PM](https://user-images.githubusercontent.com/62864373/106171564-af20bd80-61b7-11eb-9f52-4cbfddcc6fa0.png)
| - The default output of `^roles` is a list of the `SelfAssignableRoles`, rather than all the roles. ![Screenshot 2021-01-28 at 4 57 11 …

[FEAT]: Concise and more functional `roles` command

---

package-lock.json
package.json
src/commandHandlers/issue.ts
src/commandHandlers/support.ts
src/config.ts

**Note:** This command search in the issues only because I couldn't find anything in [GitHub documentation](https://docs.github.com/en/free-pro-team@latest/rest/reference/search#search-issues-and-pull-requests) to search through the discussions. 
closes #183

Feature: Find issues in the support repository

---

.github/ISSUE_TEMPLATE/docs.md
.github/ISSUE_TEMPLATE/ideas.md

This issue resolves #421 where the repo is lacking issue templates. I haven't tried in action coz of limited access, but if merged let's see if it works! ;)

Add more issue templates

---

src/timezone.ts

closes #454 
If no timezone matched, skip

fix: timezone must be matched (#454)

---

src/config.ts

added `mlh_guild` role and description
Fixes Issue #464

added mlh_guild role

---

.gitignore

Issue #469 
Added Visual Studio Code to .gitignore file.

add VSCode to .gitignore file

---

src/config.ts

Add the word GIMP to allowed word list

---

src/commandHandlers/tips/opensource.ts

Updated opensource.ts file - code optimization

---

tips/openSourceResources.md

This commit is in response to the conversation from Issue #297 about adding more open source resources for first timers.
Also changed the markdown to look as intended.
:+1: 😄

Added links from Issue #297

---

src/config.ts

Added the words superman, superwoman and hero to the list of allowed words.
Closes #419

fix : added words to allowed-words list

---

src/config.ts

Added the word `tinker` to whitelist.

---

.github/workflows/release.yml

feat: changelog and release (#501)

---

src/alexjs/alex.service.ts
src/config.ts

feat: flag custom words (#461)

---

src/config.ts

Add Jesus To Allowed List

---

src/config.ts

Added fellow word

---

src/alexjs/alex.service.ts

The Language System Was Having Some Issues With "Sir" in cases, discussed on discord with @eddiejaoude @Vyvy-vi and @verma-kunal

Fix Case Sensitivity

---

src/alexjs/alex.service.ts

fix: check for multiple words

---

src/alexjs/alex.handler.ts
src/alexjs/alex.service.ts

feat: alert removal (#339)

---

src/alexjs/alex.service.ts

fixes #552 
I think when doing intellisense I took the wrong `toLowerCase`-function

Fix: update Issue 552 with function

---

src/config.ts

Added women to prevent words list

---

src/alexjs/alex.handler.ts

feat: delete notification on messageDelete

---

src/alexjs/alex.handler.ts

Use the right property to find the notification message.
TODO: we should probably rename these properties a bit better.

fix: fix my fix

---

src/app.module.ts
src/check-image/check-image.handler.ts
src/check-image/check-image.module.ts
src/check-image/check-image.service.ts

closes #300 
In case a user uses the default-profile-picture, the bot will message him after 3 messages to a channel and asks him to consider setting a profile-picture.
The actual message-text and the amount of messages are open for discussions

Check default image

---

src/alexjs/alex.service.ts

Updated the warning message from:
'This might not be inclusive or welcoming language. Please consider the following suggestions instead:',
to
'This might not be inclusive or welcoming language. Please update / edit your message with the following suggestions instead:',

Updated the warning message

---

kubernetes/deployment.yaml

fix: use api token (#587)

---

README.md

Discord docs were missing in the Readme.md earlier. Now its added , I will be adding more links in the future.

Discord docs added

---

src/config.ts

Fixes #613 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/EddieBot/pull/615"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Allow the usage of word "just"

---

src/config.ts

also solved lint (prettier) issue
closes #617
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/EddieBot/pull/619"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

added 'fellas' to banned words

---

package-lock.json
src/config.ts

Closes #607 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/EddieBot/pull/621"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added versions of `mam` to banned words

---

package-lock.json
src/config.ts

Things added/changed:
- Add `yessir` to the list of blocked words.
- `package-lock.json` was modified automatically, not sure why. 🤷‍♂️
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/EddieBot/pull/629"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add `yessir` to the list of blocked words

---

src/config.ts

Fixed #635
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/EddieBot/pull/636"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

[OTHER] Added simp to block list

---

src/config.ts

Pull request to resolve issue #675
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/EddieBot/pull/676"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Removed duplicate term from filter list

---

src/config.ts

No warning for bhaiya 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/EddieBot/pull/679"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: block 'bhaiya'

---

CODE_OF_CONDUCT.md

I have also updated the contact information to `community@eddiehub.org`
closes: #678 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/EddieBot/pull/681"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

docs: updated Code of Conduct to v2.1

---

README.md

Improved Documentation
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/EddieBot/pull/666"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Update README issue #664

---

README.md

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/EddieBot/pull/728"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

docs: Contributors section added

---

CONTRIBUTING.md
README.md

Fixed little typos in the Readme and Contributing file.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/EddieBot/pull/735"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fixed little typos in readme and contributing file

---

.github/workflows/kubescape.yml

Closes #752 
- [] The title of my pull request is a short description of the requested changes.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/EddieBot/pull/753"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

ci: add kubescape action

---

src/config/BannedWordsOptions.ts

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/EddieBot/pull/757"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: alternative ban word

---

src/config/BannedWordsOptions.ts

Word 'dudez' is added to BannedWordsoptions file.

---

src/events/onMessage.ts
src/events/onUpdate.ts
src/links/checkLinks.ts

feat: checks for links

---

src/database/connectDb.ts
src/events/onMessage.ts
src/links/checkLinks.ts

feat: log removed messages to admin channel

---

src/links/checkLinks.ts

fix: url check

---

src/links/checkLinks.ts

feat: ignore link check for role

---

.github/workflows/deploy
captain-definition

feat: gh action deploy

---

.github/workflows/build.yml
.github/workflows/docker.yml
.github/workflows/kubescape.yml
.github/workflows/labels.yml
.github/workflows/release.yml

Closes #806 
Update actions dependencies to latest version.
Update setup-node versions to 20, the current LTS

Update action dependencies to latest versions

---

.github/workflows/release.yml

Closes #807 
Switch action that generates release to [softprops/action-gh-release](https://github.com/softprops/action-gh-release)

fix: switch release action to softprops/action-gh-release

---

README.md

closes #795 
I have added the open with GitPod button
Preview:

docs: add Gitpod button in README

---

src/typo/dict/en_US/dictionaries.md
src/typo/dict/en_US/en_US.aff
src/typo/dict/en_US/en_US.dic

Update the Hunspell dictionaries

Update Dictionaries for Typo
