src/commandHandlers/codeOfConduct.ts
src/commandHandlers/fallback.ts
src/commandHandlers/help.ts
src/commandHandlers/index.ts
src/commands.ts
src/config.ts

Added in a commandHandlers folder where you can place commands in their own files.
Also added in a configuration file for setting the default command prefix and embed code.
This allows for adding in commands easier and not having one giant commands file filled up and hard to read.

feat(commandSplitting): #38 Move commands to their own file

---

README.md
src/commands.ts
src/index.ts
src/stats/discordStatsService.ts
src/stats/statsService.ts

This PR only implements one of the tasks for this feature for now. The idea is to keep developing the **stats feature** in this PR. The function `getServerMemberCount()` uses the Discord API to get the number of total users.
Like it was discussed on the issue #35, this data can come from a DB later on. Which means the current implementation can be improved to support this, without changing the `commands.ts` file. By moving the function `getServerMemberCount` (and possible others like getTotalMessages, etc) to an interface, the `commands` module isn't coupled to an implementation, and we can decide to fetch from the DB or Discord API. Overall this would improve the encapsulation of the code.
Let me know your thoughts 🙂.
---
_Edit: 30/05/2020_
- A new command was added: `!stats`
- Added the …

Feature 35 server stats command

---

src/commandHandlers/standup.ts
src/commands.ts

_Note:_ If you try to test this change locally, you'll need to add the **Manage Messages** permission to the bot, or you will get an error. For more info. read [these docs](https://discordjs.guide/popular-topics/permissions-extended.html#missing-permissions)
Closes: #55

fix(standup): delete user's message and add user info in footer

---

README.md
src/client.ts

> ⚠️ Before merging this change, @eddiejaoude you need to go to Dev Portal and enable the **SERVER MEMBERS INTENT**, because we use one [privileged intent](https://discordjs.guide/popular-topics/intents.html#privileged-intents).
Anyone testing this can check more information [here](https://support.discord.com/hc/en-us/articles/360040720412-Bot-Verification-and-Data-Whitelisting#privileged-intent-whitelisting). I don't think we need to verify the bot for now since **it's not in 100 servers**, so enabling that toggle on the Dev Portal, under the Bot menu, should be enough:
Closes: #36

Add Gateway Intents to the discord client

---

src/commandHandlers/bio.ts
src/config.ts

closes #86 
Users that set any `bio` info, they get a the role `bio` which makes their name blue

feat(bio): when user sets any bio, give them bio role

---

src/config.ts

> Asia/India doesnt exist in momentjs but apparently the same time zone identifier they use is Asia/Kolkata which is IST

fix(timezone): fixed IST timezone #89

---

src/commandHandlers/guild.service.ts
src/commandHandlers/index.ts
src/commandHandlers/roles.ts

Issue: #74
**Questions**
- Where will we store the role description?
- Do we implement a different command to assign roles to users (`$iam <role>`) on this PR?
_Note_: I was thinking of renaming `guild.service` to `roles.service` but I think our idea of a **service** module could be more geared for the **Domain Model**, and not a feature. So this file would have more functions related to `Guilds` (basically the `discordClient.guilds` field from the discord.js API)

feat(roles): add roles command

---

src/config.ts
src/timezone.ts

closes #106 
`UK` is an alias for `UTC` (because I always write UK 🤦 ) as spotted by @alrifay - great spot 👍

feat(timezone): utc has an alias of uk

---

src/messageReactionAdd.ts

closes #210 
This patch will not allow the assignment of `High Value` role to moderators.

fix(messageReactionAdd): ignore moderators #210

---

src/logger.ts
src/opensourceReminder.job.ts
src/scheduler.service.ts

Refactored the code block that gets the subscribedUsers into its own function, instead of having a comment.
These trace logs and the stack trace (in logger.ts) should give us more information where the error of this issue is coming from (Firestore or Discord.js).
@eddiejaoude do you think we could deploy this change to EddieBotDev and add `LOG_LEVEL=trace` when running the bot? I couldn't reproduce the error locally, so I'm not sure what is causing it. This PR wouldn't close the issue, just help us debug it.
Issue: #221

refactor: add trace logs to open source reminder

---

README.md

closes #235 
We will use the default contributors provided by GitHub so it is always up to date...

feat(contributors): remove all contributors #235

---

src/commandHandlers/tips/opensource.service.ts
src/commandHandlers/tips/opensource.ts
src/commandHandlers/tips/tips.ts
src/config.ts

closes #253 
This could probably be split up into more arguments later on, for example
- `^tips opensource`
- `^tips github`

feat(tips): load files from config

---

package-lock.json
package.json
src/commandHandlers/fallback.ts
src/commandHandlers/index.ts
src/commands.ts
src/suggestSimilarCommands.ts

closes #245
* ### No similar commands
* ### Single similar command
* ### Multiple similar commands

feat: similar commands

---

README.md
src/commandHandlers/bio.ts
src/commandHandlers/codeOfConduct.ts
src/commandHandlers/fallback.ts
src/commandHandlers/help.ts
src/commandHandlers/iam.ts
src/commandHandlers/index.ts
src/commandHandlers/issue.ts
src/commandHandlers/reminder.ts
src/commandHandlers/roles.ts
src/commandHandlers/standup.ts
src/commandHandlers/stats.ts
src/commandHandlers/support.ts
src/commandHandlers/tips/tips.ts
src/commands.ts

fixes #291
@BOLT04 I tried to do it a little differently:
```diff
- arg: string // Here, arg was represented the string of arguments passed to each command.
+ arg: [string, string] // Here, arg[0] represents the command name and arg[1] represents the string of arguments passed to the command.
```
because this fits in a little easily without having to execute the `args.slice(command.length + 1)` in every `commandHandler`.

refactor: changed interface of commandHandler

---

src/config.ts

Added Korean timezone. It's from #232. After adding all timezones, then chat screen will be full as @AllanRegush said. Seems bot doesn't have to show all time zones.

fix(issue): Added Korean timezone

---

src/config.ts

While exploring the role-adding feature in the Discord server, I discovered that I couldn't add the `node` role to myself. A bit of digging suggests that it was missing from the `selfAssignableRoles` config, so I've added it in (as well as the two other tech-based roles I saw were missing).

Add missing roles

---

src/config.ts

fix: adding 'host' to ignore list

---

src/config.ts

Brief: Added the word of course to the ignore list as mentioned in #333 
I'd appreciate any suggestions or changes.

fix(bot): Added 'of course' to the ignore list

---

.huskyrc
package-lock.json
package.json

closes #341 
Leverages `husky` and `lint-staged` to run the linter and formatter on `.ts` files before committing them. This should prevent errors where a contributor forgets to run the linter before committing/opening a PR.

Add pre-commit linting

---

src/config.ts

Brief: Added the words 'fellow' and 'fellowship' to the ignore list as mentioned in #350

fix(bot): Added 'fellow' and 'fellowship' to the ignore list 

---

src/config.ts

Added the word 'pop' to the EddieBot ignore list as per issue #349

fix(bot) : Added 'pop' to ignore list

---

README.md

regarding #358 and [Support #469](https://github.com/EddieJaoudeCommunity/support/issues/469)
Removes `all-contributors` badge, since it isn't used, and is out of date.

fix: remove all-contributors badge

---

src/config.ts
src/words.ts

This PR adds a regex to replace the punctuation in `message.content` fetched from messages, to get normal text strings.
Regex used:
`message.content.replace(/[.,/#!$%&*;:{}=\-_'"~()]/g, ' ').replace(/\s{2,}/g, ' ');`
Is there any way to make this better or to include more flags, to ensure that this reduces as much loopholes in Alex, as possible? Any suggestions would be great :)
| **Before this PR** | **After this PR**  |
| ------------------ | ----------------- |
| easy = `gets flagged`| easy = `gets flagged`| 
| , easy, = `not flagged`| , easy, = `gets flagged`|
| `easy` = `not flagged`| `easy` = `not flagged`|
| -easy- = `not flagged`| -easy- = `gets flagged`|
| "easy" = `not flagged`| "easy" = `gets flagged`|
*_the word `easy` has been used as a convenient example here_
| **Before …

[FEAT]: optimised word filter(alex)

---

src/words.ts

This PR introduces small changes to `src/words.ts`, to prevent Alex from returning multiple reminders(flags) for the same word repeated a no. of times.
The message string(after the special characters are removed), is converted into an array, which is converted to a set, and joined back with spaces in between as a string.
**AFTER**
Issue: closes #357

[fix]: fixed multiple reminders for same word

---

src/config.ts

Allows the use of `Mexican` instead of recommending `Latinx`.
Ref: [Discord conversation](https://discord.com/channels/699608417039286293/717736706555641986/802637940211580990)
**Note:** This will also stop flagging `Latino` and `Latina` - take into consideration before merging.

fix: allow the use of Mexican

---

src/config.ts

Allows `postman` (also, `postwoman`, unfortunately) to stop flagging
our use of the software by the same name.
Ref: https://discord.com/channels/699608417039286293/699609489699110943/803734701382565918

fix: allow `postman`

---

src/config.ts

Adds a self-assignable community chat role.
Screenshots:

feat: add community chat role

---

src/config.ts

Adds an among us role that functions similar to the community chat role.

feat: among us role

---

src/config.ts

`retext` maintains a separate rule for `host` vs `hosts`. This adds `hosts` to the allow-list.
Ref: https://discord.com/channels/699608417039286293/699609729353384036/806302465552547920

fix(alex): allow hosts

---

src/config.ts

This adds the battlesnake role to the self-assignable role list of the bot. : )
closes #444

feat: assignable battlesnake role

---

src/words.ts

This PR adds `?` to the `words.ts` regex to `stripSpecialCharacters` before sending them through Alex.js
| Before | After |
| --- | --- |
| ![he he? gets flagged](https://user-images.githubusercontent.com/43912470/108365179-ea456800-721c-11eb-8575-9e7c61c9d49e.png) | ![he he not flagged](https://user-images.githubusercontent.com/62864373/108430840-01f60e00-7268-11eb-81bf-262920564639.png) |
closes #447

fix: added ? to special character strip regex

---

src/config.ts

replaced mlh_guild to mlh-guild in self assignable roles
Closes #467

replaced mlh_guild to mlh-guild

---

src/words.ts

closes #460 
This PR adds Left quote `“` and right quote `”` to the special characters regex. Removing the ability to escape warnings from the bot.

fix(words): matching special unicode qoutes #460

---

.gitignore

Fixes #469 
Added `.idea/` to the `.gitignore` file.
*Why are we not using a template?*

Added .gitignore for IDEs

---

src/commandHandlers/roles.ts

closes #446
This PR fixes the `^roles` embed, which used to give assignment suggestion for non-assignable roles.
That might have been misleading to people.
A check to see if the role is in selfAssignableRoles.
(Could their be better ways of doing this rather than using `.includes()`?)
**Before-** 
**After-**

Corrected role assignment embed

---

package.json

#496 
Changed the license type from `UNLICENSED` to `MIT` 
```diff
- "license": "UNLICENSED",
+ "license": "MIT",
```

ref: :hammer_and_wrench: : License section updated in package.json

---

src/alexjs/alex.handler.ts

We have existing logic to delete the notification data from our
"database", but not the actual Discord message. This commit adds
logic to delete the actual Discord message.

fix: delete notificaiton message

---

src/config.ts

Fixes issue #570
The bot used to prompt Kushi as a profane word but in this fix, Kushi is added to the allowed list.

Added "Kushi" to the allowed list

---

src/alexjs/alex.handler.ts
src/alexjs/alex.service.ts

Following fixes made:
- Block code blocks (fix #602)
- Block words escaped using `\`
- Fix some upcoming errors (unhandled catch errors)

Fix Regex to show errors for backticks and `/`

---

src/config.ts

Things added/changed:
- Add `chad` to the list of blocked words.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/EddieBot/pull/632"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chad blocked word

---

src/alexjs/alex.service.ts
src/config.ts

closes #627 
From the AlexJS docs the word `fellow` is grouped as part of `gal-guy` 
> woman (female), gal (female), lady (female), babe (female), bimbo (female), chick (female), guy (male), lad (male), fellow (male), dude (male), bro (male), gentleman (male)
https://github.com/retextjs/retext-equality/blob/main/rules.md
We need to write a wrapping around AlexJS to be more granular, as we want to block most of these words but want to allow some.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/EddieBot/pull/628"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat: granula AlexJS ignore (#627)

---

src/config.ts

I have added `boys` to the blocklist/ prevent words recommended by @eddiejaoude 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/EddieBot/pull/658"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add "boys" to block list

---

src/alexjs/alex.service.ts

In code blocks, it is usually to explain people
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/EddieBot/pull/683"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: allow codeblocks

---

.github/PULL_REQUEST_TEMPLATE/pull.md

Setting up a Pull Request File.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/EddieBot/pull/714"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Creating Pull Request File - Pull.md

---

package-lock.json

All versions of package trim lower than 0.0.3 are vulnerable to Regular Expression Denial of Service (ReDoS) via trim().
on trim in [package-lock.json](https://github.com/EddieHubCommunity/EddieBot/blob/-/package-lock.json).
upgrade trim to version 0.0.3 or later. For example:
```json
"dependencies": {
"trim": ">=0.0.3"
}
```
```json
"devDependencies": {
"trim": ">=0.0.3"
}
```
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/EddieBot/pull/743"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

CVE-2020-7753

---

src/database/connectDb.ts

fix: mongo does not need cert file

---

README.md

Envars added to the README docs

---

.github/workflows/codeql.yml

Enable CodeQL security scanning

test: use CodeQL scanning

---

src/events/onMessage.ts
src/events/onUpdate.ts

Messages containing an invalid link are deleted
Continuing to check the message is unnecessary

fix: invalid link deletes message, so stop checking

---

src/links/checkLinks.ts

It is possible currently to hide a link by capitalizing a letter in the http protocol.
This PR changes the regex to check for either case

fix: handle http protocol capitalization when checking links

---

src/alexjs/checkBannedWords.ts
src/config/UrlRegex.ts
src/links/checkLinks.ts

fix: remove URLs from content before checking for banned words
